name: "Setup Arduino CLI"
description: "Download Arduino CLI and add it to the PATH"
author: "Arduino"
inputs:
  version:
    description: "Version to use. Example: (1.0.1, 1.0.x, 1.x)"
    default: "1.x"
  token:
    description: "Personal access token (PAT) used to call the Github API."
    required: false
    default: ${{ github.token }}
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "box"
  color: "green"
